### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wangjx22** [lsh0520/3D-MoLM#2]
May I ask the dataset from [Huggingface-3D-MoIT](https://huggingface.co/datasets/Sihangli/3D-MoIT) is the raw data or enriched by GPT3.5？

**Comment by lsh0520** [comment]
Hi, thank you for your interest in our work.

Both are provided in 3D-MoIT. Please check /data_provider/unimol_dataset.py (around line 70) for detailes.
