### ISSUE TITLE
package problem

### ISSUE THREAD

**Issue by wangjx22** [lsh0520/3D-MoLM#4]
hello, I am try to run the stage1.py.
But, got an error: ModuleNotFoundError: No module named 'lavis'
the code issue is: from lavis.models.blip2_models.blip2 import in the line 17 and line 20 of 3D-MoLM/model/blip2qformer.py

How to address it? Thanks!

**Comment by acharkq** [comment]
You can install the lavis package by running

pip install salesforce-lavis

**Comment by wangjx22** [comment]
Thanks!
