### ISSUE TITLE
Stage1 and stage2 checkpoints

### ISSUE THREAD

**Issue by icycookies** [lsh0520/3D-MoLM#7]
Thanks for your efforts in releasing this inspiring work! However, it seems that the provided generalist model is the checkpoint after stage3 pre-training. I wonder if the authors could provide the pre-trained checkpoints after stage1 and stage2 for evaluating molecule-text retrieval and molecule captioning.

**Comment by lsh0520** [comment]
Thanks for your interest in our work. Will release them in a week.

**Comment by lsh0520** [comment]
Hi, we haved uploaded stage1 & stage2 ckpts to huggingface. Please check the **Checkpoints** section in updated README file to reproduce all the results (Table 2&3&4) in the paper.

**Comment by icycookies** [comment]
Thanks for your quick reply!
