### ISSUE TITLE
About the enriched Pubchem324K dataset

### ISSUE THREAD

**Issue by lhkhiem28** [lsh0520/3D-MoLM#9]
I just came across your recent work 3D-MoLM and it's very impressive. I noticed that you leveraged ChatGPT to enrich the Pubchem324K dataset, but I cannot find the enriched Pubchem324K in your repos (Github and HuggingFace).

Can this enriched dataset made accessible? If yes, could you please share it with me?

Thanks!

**Comment by lsh0520** [comment]
Thanks for your interest in our work. Both raw and enriched description are provided in the LMBD database of 3D-MoIT. Please check /data_provider/unimol_dataset.py (around line 70) to read them.
